### PR TITLE
switch to yarn 2 and add webpack 5 support. drop webpack 2-3

### LINKED ISSUE #13: webpack 5 support
Hi. Is this plugin still being maintained? Any plans to add support for webpack 5?

### PR DESCRIPTION
**Pull request by bdwain**
fixes #13 

I updated the plugin to support webpack 5. It seems like webpack 4 still works, but 2-3 stopped working. So i guess this would be a breaking change.

@x1B i also switched the repo to use yarn 2, including [yarn pnp](https://yarnpkg.com/features/pnp) and [zero installs](https://yarnpkg.com/features/zero-installs). It means you no longer need to run yarn install, and there's no more node modules directory. Instead, the cache directory (which is much smaller than the node_modules dir) is committed to the repo. If you don't like that, I'm happy to revert some or all of those changes. Just let me know. If we turn off zero installs, the cache directory will be git ignored, but we can keep yarn pnp. If we turn off pnp, then we'd also turn off zero installs and bring back a node modules dir. Or we can go back to yarn 1 and turn off all of the changes.

### CODE REVIEW

**Comment by bdwain** [comment]
@x1B anychance you can take a look at this?

**Comment by bdwain** [comment]
@x1B ?

**Comment by bdwain** [comment]
@x1B do you still maintain this repo? I'd love to get this change in so that this can be used with webpack 5

**Comment by x1B** [comment]
@bdwain sorry for not getting back to you sooner. I'm afraid I won't be able to review/merge your changes anytime soon. Since it's a fairly substantial change wrt infrastructure, I suggest forking the repo and publishing your modernized version on NPM.

**Pull request closed without merging**
