### PR TITLE
upgrade peer dependencies to allow latest webpack and jasmine

### PR DESCRIPTION
**Pull request by bdwain**
It looks like there were no breakages for the new version, so I think both can be supported for now

This will address #11

### CODE REVIEW

**Comment by x1B** [comment]
@bdwain thanks for the fix — I'll try to release it on NPM asap

**Comment by bdwain** [comment]
Thanks!

**Comment by x1B** [comment]
@bdwain 0.9.0 is on NPM now, should include your PR 👍

**Comment by bdwain** [comment]
awesome!

**Pull request merged**
